### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 66

### ISSUE THREAD

**Issue by ohyeah521** [ajinabraham/libsast#30]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Python3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python3\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\Python3\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\Python3\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Python3\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66

**Comment by ajinabraham** [comment]
Are you on latest Python?
This might be related: https://github.com/pycaret/pycaret/issues/38#issuecomment-676963390

**Comment by ohyeah521** [comment]
C:\Users\>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by ajinabraham** [comment]
64 logical processors that's it. I am trying a fix.

**Comment by ajinabraham** [comment]
I pushed a possible fix. Can you try `libsast 2.0.1` and see if that fixes it?

**Comment by ohyeah521** [comment]
This version of libsast 2.0.1 works properly
